- name: Notify Kafka - Job Failed
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Send Kafka failure notification
      include_role:
        name: kafka_notify
      vars:
        kafka_outcome_type: "PROVIDER_OPERATION_FAILED"
        kafka_payload: >-
          {{
            {
              "requestId": request_id,
              "requestType": request_type,
              "externalId": external_id,
              "userEmail": user_email,
              "error": error,
              "errorDetail": errorDetail
            } | to_json
          }}