- name: Notify Kafka - Job Success
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install kafka-python
      pip:
        name: kafka-python
        state: present
        extra_args: --break-system-packages

    - name: Write Kafka CA certificate
      copy:
        content: "{{ kafka_ssl_cafile }}"
        dest: /tmp/kafka_ca.pem
        mode: '0600'

    - name: Test connessione SSL con openssl
      shell: |
        openssl s_client -connect manageiq-kvm.corp.sourcesense.com:9093 -CAfile /tmp/kafka_ca.pem < /dev/null
      register: openssl_debug

    - name: Debug OpenSSL connection
      debug:
        var: openssl_debug.stdout_lines

    - name: Send success message to Kafka
      shell: |
        python3 -c "
        from kafka import KafkaProducer
        import json, ssl
        from datetime import datetime

        ssl_context = ssl.create_default_context(cafile='/tmp/kafka_ca.pem')
        ssl_context.check_hostname = False

        producer = KafkaProducer(
          bootstrap_servers='{{ kafka_bootstrap_servers }}',
          security_protocol='SASL_SSL',
          sasl_mechanism='{{ kafka_sasl_mechanism }}',
          sasl_plain_username='{{ kafka_username }}',
          sasl_plain_password='{{ kafka_password }}',
          ssl_context=ssl_context,
          key_serializer=lambda v: json.dumps(v).encode('utf-8'),
          value_serializer=lambda v: json.dumps(v).encode('utf-8')
        )

        key = {
          'providerId': '{{ provider_id }}',
          'outcomeType': 'PROVIDER_OPERATION_COMPLETED',
          'timestamp': datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
        }

        payload = {
          'requestId': '{{ request_id }}',
          'externalId': '{{ external_id }}',
          'userEmail': '{{ user_email }}',
          'cloudBlueTemplateId': '{{ cloudblue_template_id }}'
        }

        producer.send('{{ kafka_topic }}', key=key, value=payload)
        producer.flush()
        producer.close()
        print('OK')
        "


#Rimosso per il momento request type 
#modificato provider_id perchè non deve prenderlo più dal secret ma dal job 
#aggiungere il time stamp giusto 
