- name: Notify Kafka - Job Failed
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Send failed message to Kafka
      shell: |
        python3 -c "
        from kafka import KafkaProducer
        import json

        producer = KafkaProducer(
          bootstrap_servers='172.16.0.174:9093',
          value_serializer=lambda v: json.dumps(v).encode('utf-8')
        )

        producer.send('topic-failed', {
          'status': 'failed',
          'job': '{{ awx_job_id }}',
          'template': '{{ awx_job_template_name }}'
        })
        producer.flush()
        producer.close()
        print('OK')
        "